server:
  port: 8071
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate.ejb.interceptor: com.alexcorp.example.hibernateinterceptor.interceptor.CustomInterceptor
    database-platform: org.hibernate.dialect.PostgreSQLDialect